name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Android Github Action
      uses: Vukan-Markovic/Github-Android-Action@1.2
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-gihub-apk.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
